### ISSUE TITLE
crontab running not changing wall paper

### ISSUE THREAD

**Issue by ixzh** [thevinter/styli.sh#31]
Hi,
I have the following crontab:`* * * * *  /path/to/styli.sh -s "dark-color" -p`

the colors are updated for terminal, but the wallpaper and polybar colors don't update.

If I run the `/path/to/styli.sh -s "dark-color" -p` directly in a terminal, it works. What could go wrong here? Thanks!!

**Comment by thevinter** [comment]
Thanks for the insightful reply. I will look into this as soon as possible and try to come up with a fix.

**Comment by simurq** [comment]
After quite a lengthy [discussion](https://www.reddit.com/r/pop_os/comments/pd8vhj/help_with_setting_crontab_command_to_run_a_bash/), the problem is solved as follows:

```
$ sudo crontab -u {username} -e
0 13 */3 * * DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus /home/{username}/path/to/styli.sh -g -d /home/{username}/path/to/images/
```
Some notes before you rush to run the job:
1. The problem discussed here concerns running _styli.sh_ with images from a local directory (`-d`) only. Otherwise, running a crontab job, where only the desktop environment tag is provided (e.g. `-g` for GNOME or `-k` for KDE, etc.), works quite well, i.e. downloads images from the web as required and does **not** need the `DBUS...` variable set.
E.g.: `0 13 */3 * * bash -c "/home/{username}/path/to/styli.sh -g"`.
2. Notice the forward slash at the end of `/path/to/images/`. 
3. Check your `DBUS_SESSION_BUS_ADDRESS` environment variable in the terminal before inserting the line to crontab, e.g. `echo $DBUS_SESSION_BUS_ADDRESS`, as yours may be set to a different user.
4. My system is based on Ubuntu (Pop_OS! 21.04) with GNOME, hence the `-g` tag. Yours may not even require setting `DBUS`... inside crontab. So, the instructions in _styli.sh_ README may well be enough in your case.
5. Finally, my crontab job is set to run [at 1pm every 3rd day of month](https://crontab.guru/#0_13_*/3_*_*), but you can set the time to your own liking.

Hope it helps!

**Comment by thevinter** [comment]
I'm really impressed by the amount of work you made to make it work so thanks for the research and the solution. I'm glad you solved the issue. 

What leaves me confused is the fact that you say that the problem only arises with the `-d` flag but @ixzh seems to have it without the flag. It's also weird because on my machine the chron job works without any problems (Arch + i3) 

Also just to clarify a thing. As users in your discussion posted remember that styli.sh changes the wallpaper for the current user so running any chronjob or service (https://github.com/thevinter/styli.sh/issues/16) as a sudo user won't work unless the user is explicitly specified. Not inherently related to the issue at hand but might prevent some issues in the future.

**Comment by simurq** [comment]
> running any chronjob or service (#16) as a sudo user won't work unless the user is explicitly specified

Thank you, a good point! That's why I explicitly run the job for my user, just to be on the safe side. With my note in point 2 above, I was actually referring to your README statement re: running a job simply with `crontab -e`, which didn't work on my machine. I hope I understood your comment right.

**Comment by ixzh** [comment]
I run the script in terminal which is ok;
I add the script to `crontab -e`, it doesn't work, but colors are updated for terminal.

**Comment by thevinter** [comment]
Could you please try running it via 

`@hourly . path/to/script/styli.sh`

(Note the `.` in the command)

**Comment by ixzh** [comment]
> Could you please try running it via
> 
> `@hourly . path/to/script/styli.sh`
> 
> (Note the `.` in the command)

hi i edit crontab -e to be: `* * * * * . /path/to/script` nothing happens...

**Comment by ixzh** [comment]
Just read somewhere else, and the problem solved:

cron doesn't use any environment variable, so the line `DISPLAY=:0 ` should be added directly before `styli.sh -p`, and the following works as expected:

```
* * * * * DISPLAY=:0 /path/to/styli.sh -s "dark-color" -p
```
